
export const ERROR_LOGIN_ON = 'ERROR_LOGIN_ON';
export const ERROR_LOGIN_OFF = 'ERROR_LOGIN_OFF';

export const ERROR_EX_LOGIN_ON = 'ERROR_EX_LOGIN_ON';
export const ERROR_EX_LOGIN_OFF = 'ERROR_EX_LOGIN_OFF';