export const TODO_CREATE = 'TODO_CREATE';
export const TODO_FIND_ALL = 'TODO_FIND_ALL';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_UPDATE_STATE = 'TODO_UPDATE_STATE';
export const TODO_SAVE_STATE = 'TODO_SAVE_STATE';
export const TODO_DELETE_ALL = 'TODO_DELETE_ALL';

